# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Deployment patches that
# - Use local container image
# - Use api-compiler to create service config
# - Make shared volume for api-compiler and ESP container

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
spec:
  selector:
    matchLabels:
      app: website-app
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  template:
    spec:
      volumes:
        - name: mixer-grpc-json
          emptyDir: {}
      containers:
        - name: website
          image: datacommons/website
          imagePullPolicy: Never
          resources:
            limits:
              memory: "1G"
        - name: mixer
          image: datacommons/mixer
          imagePullPolicy: Never
          resources:
            limits:
              memory: "1G"
        - name: esp
          volumeMounts:
            - mountPath: /esp
              name: mixer-grpc-json
        - name: api-compiler
          image: datacommons/api-compiler
          imagePullPolicy: Never
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              cp /output/mixer-grpc.json /esp/ &&
              while true; do
                echo "api-compiler running"
                sleep 3600;
              done
          volumeMounts:
            - name: mixer-grpc-json
              mountPath: /esp
          readinessProbe:
            exec:
              command: ["ls", "/esp/mixer-grpc.json"]
            periodSeconds: 1
