# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Helm config
project: "datcom-bard"
cluster_prefix: "website"

namespace:
  name: "website"

website:
  flaskEnv: custom
  replicas: 20
  redis:
    enabled: true
    configFile: |
      {
        "us-central1": {
          "host": "10.83.62.11",
          "port": "6379"
        }
      }

serviceAccount:
  name: website-ksa

ingress:
  enabled: true
  internal: true

nl:
  enabled: true

nodejs:
  enabled: true
  replicas: 25

serviceGroups:
  recon: null
  svg:
    replicas: 6
  node:
    replicas: 15
  observation:
    replicas: 15
  default:
    replicas: 9

svg:
  blocklistFile: ["dc/g/Uncategorized", "oecd/g/OECD"]

cronTesting:
  enabled: true
  enableSanity: false
