# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Helm config
project: techsoup-data-commons
cluster_prefix: datacommons

namespace:
  name: website

website:
  image:
    project: techsoup-data-commons
    tag: 1838055 
  flaskEnv: custom
  replicas: 1

ingress:
  enabled: true

mixer:
  useBranchBigtable: false
  useCustomBigtable: true

serviceAccount:
  name: website-ksa

nl:
  enabled: false

serviceGroups:
  recon: null
  svg: null
  observation: null
  node: null
  default:
    replicas: 1
    useSearch: true
    resources:
      memoryRequest: "8G"
      memoryLimit: "8G"

kgStoreConfig:
  customBigtableInfo: |
    project: techsoup-data-commons
    instance: dc-graph
    tables:
      - mealsites_places_exp_2023_06_02_18_41_11
      - usda_grocery_access_2023_05_22_11_28_04
      - fea_grocery_access_2023_06_01_18_49_10
      - fea_store_availabili_2023_06_06_12_25_22
      - irs_registered_nonpr_2023_06_07_11_02_15
      - techsoup_served_nonp_2023_06_07_13_27_15

svg:
  blocklistFile: ["dc/g/Uncategorized", "oecd/g/OECD"]
