
project: "datcom-website-prod"
mixer:
  hostProject: "datcom-website-prod"
  serviceName: "website-esp.endpoints.datcom-website-prod.cloud.goog"
  useRedis: false
  redis:
    enabled: true
    configFile: |
      instances:
        - region: "us-central1"
          host: "10.167.58.139"
          port: "6379"
        - region: "us-west1"
          host: "10.158.101.59"
          port: "6379"
  enableOtlp: true

serviceAccount:
  name: website-ksa

# Disable ingress for mixer in datcom-website-prod (Sidecar only)
ingress:
  enabled: false