# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Kustomization for the Feeding America deployment.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -feedingamerica
namespace: website

resources:
  - ../../base

configMapGenerator:
  - behavior: merge
    literals:
      - flaskEnv=feedingamerica
    name: website-configmap
  - behavior: create
    literals:
      - hostProject=datcom-feedingamerica
      - serviceName=website-esp.endpoints.datcom-feedingamerica.cloud.goog
    name: mixer-configmap
  - name: memdb-config
    behavior: replace
    files:
      - memdb.json
  - name: redis-config
    files:
      - redis.json

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: website-app
    spec:
      replicas: 6
      template:
        spec:
          volumes:
            - name: redis-config
              configMap:
                name: redis-config
          containers:
            - name: website
              volumeMounts:
                - name: redis-config
                  mountPath: /datacommons/redis

patchesJson6902:
  - path: patch.yaml
    target:
      group: apps
      kind: Deployment
      name: website-app
      version: v1
