# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: datacommons-website
description: My application delivery pipeline for DataCommons Website (and associated Mixer)
serialPipeline:
  stages:
    - targetId: website-dev
      profiles: [website-dev]
      deployParameters:
      - values:
        website.githash: ${WEBSITE_GITHASH}
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-dev"]
            # actions: ["deploy-cloud-esp-dev", "update-bigtable-info", "debug-cat-file"]
          postdeploy:
            actions: ["clear-website-cache"]
    - targetId: website-autopush
      profiles: [website-autopush]
      deployParameters:
      - values:
        website.githash: ${WEBSITE_GITHASH}
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-autopush"]
            # actions: ["deploy-cloud-esp-autopush", "update-bigtable-info"]
          postdeploy:
            actions: ["clear-website-cache"]
    - targetId: website-staging
      profiles: [website-staging]
      deployParameters:
      - values:
        website.githash: ${WEBSITE_GITHASH}
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-staging"]
          postdeploy:
            actions: ["clear-website-cache", "run-percy-snapshots"]
    - targetId: website-prod
      profiles: [website-prod]
      deployParameters:
      - values:
        website.githash: ${WEBSITE_GITHASH}
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-prod"]
          postdeploy:
            actions: ["clear-website-cache", "run-percy-snapshots"]

---

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: datacommons-mixer
description: My application delivery pipeline for DataCommons Mixer API cluster
serialPipeline:
  stages:
    - targetId: mixer-dev
      profiles: [mixer-dev]
      deployParameters:
      - values:
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-mixer-dev"]
            # actions: ["deploy-cloud-esp-mixer-dev", "update-bigtable-info"]
    - targetId: mixer-autopush
      profiles: [mixer-autopush]
      deployParameters:
      - values:
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-mixer-autopush"]
          postdeploy:
            actions: ["clear-mixer-cache"]
    - targetId: mixer-staging
      profiles: [mixer-staging]
      deployParameters:
      - values:
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-mixer-staging"]
          postdeploy:
            actions: ["update-nl-integration-test-goldens"]
    - targetId: mixer-prod
      profiles: [mixer-prod]
      deployParameters:
      - values:
        mixer.githash: ${MIXER_GITHASH}
        MIXER_GITHASH: ${MIXER_GITHASH}
      strategy:
        standard:
          predeploy:
            actions: ["deploy-cloud-esp-mixer-prod"]

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: website-dev
description: Development GKE cluster for the website in project datcom-website-dev
gke:
  cluster: projects/datcom-website-dev/locations/us-central1/clusters/website-us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: mixer-dev
description: Development GKE cluster for the mixer in project datcom-mixer-dev
gke:
  cluster: projects/datcom-mixer-dev-316822/locations/us-central1/clusters/mixer-us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: website-autopush
description: Development GKE cluster for the website in project datcom-website-autopush
gke:
  cluster: projects/datcom-website-autopush/locations/us-central1/clusters/website-us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: mixer-autopush
description: Development GKE cluster for the mixer in project datcom-mixer-autopush
gke:
  cluster: projects/datcom-mixer-autopush/locations/us-central1/clusters/mixer-us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: website-staging
description: Development GKE cluster for the website in project datcom-website-staging
gke:
  cluster: projects/datcom-website-staging/locations/us-central1/clusters/website-us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: mixer-staging
description: Development GKE cluster for the mixer in project datcom-mixer-staging
gke:
  cluster: projects/datcom-mixer-staging/locations/us-central1/clusters/mixer-us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: website-prod
description: A multi-target for production deployments to multiple clusters
requireApproval: true
multiTarget:
  targetIds:
  - website-prod-central
  - website-prod-west
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: website-prod-central
description: Production GKE cluster for the website in us-central1
gke:
  cluster: projects/datcom-website-prod/locations/us-central1/clusters/website-us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: website-prod-west
description: Production GKE cluster for the website in us-west1
gke:
  cluster: projects/datcom-website-prod/locations/us-west1/clusters/website-us-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: mixer-prod
description: Development GKE cluster for the mixer in project datcom-mixer
requireApproval: true
gke:
  cluster: projects/datcom-mixer/locations/us-central1/clusters/mixer-us-central1
